### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by sten1860** [kristjanbjarni/osd-subtitles#1]
I have tried multiples times but can never this it work. 

Using data recorded from DJI goggles, telemetry set at 0.5seconds and VLC player.

**Comment by kristjanbjarni** [comment]
Are you using the correct file? You should use the csv file on the SD card on from the transmitter. What RX are you using? FrSky? Since this project has only been tested with FrSky and Crossfire it may not work for other telemetry but there have been some fixes since you created this issue so you may want to try again. If you want you can attach the log file here or send it in email at kristjanbjarni@gmail.com if you prefer so I can test this better.
